//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Magnorama_Input : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.magnorama_Input_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadClick
        {
            get
            {
                return SteamVR_Actions.magnorama_Input_PadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadTouch
        {
            get
            {
                return SteamVR_Actions.magnorama_Input_PadTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PadTouch2D
        {
            get
            {
                return SteamVR_Actions.magnorama_Input_PadTouch2D;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.magnorama_Input_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.magnorama_Input_Grip;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.magnorama_Input_Haptic;
            }
        }
    }
}
